-- Add migration script here
CREATE TABLE scm_codemap (
    id VARCHAR(36) PRIMARY KEY
    , category VARCHAR(50) UNIQUE NOT NULL
    , code VARCHAR(100) NOT NULL
    , name VARCHAR(100) NOT NULL
    , description VARCHAR(300)
    , created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    , updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE scm_config (
    id VARCHAR(36) PRIMARY KEY
    , category VARCHAR(50) UNIQUE NOT NULL
    , code VARCHAR(100) NOT NULL
    , name VARCHAR(100) NOT NULL
    , description VARCHAR(300)
    , created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    , updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE uam_user (
    id VARCHAR(36) PRIMARY KEY
    , user_name VARCHAR(100) UNIQUE NOT NULL
    , pswd_hash VARCHAR(200) NOT NULL
    , email VARCHAR(100) NOT NULL
    , created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    , updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
