-- Add migration script here
CREATE TABLE product (
    id VARCHAR(36) PRIMARY KEY
    , sku VARCHAR(100) NOT NULL
    , version_number INTEGER NOT NULL
    , created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    , updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);