-- Add migration script here
CREATE TABLE batch (
    id VARCHAR(36) PRIMARY KEY
    , reference VARCHAR(50) NOT NULL
    , sku VARCHAR(100) NOT NULL
    , qty INTEGER NOT NULL
    , eta TIMESTAMP WITH TIME ZONE
    , created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    , updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE order_line (
    id VARCHAR(36) PRIMARY KEY
    , sku VARCHAR(50) NOT NULL
    , qty INTEGER NOT NULL
    , created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    , updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE allocation (
    id VARCHAR(36) PRIMARY KEY
    , batch_id VARCHAR(100) NOT NULL
    , order_line_id VARCHAR(100) NOT NULL
    , created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    , updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
